---
abstract: 'Record/restore LWP response using __DATA__ section'
author:
  - 'motemen <motemen@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: LWPx-Record-DataSection
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  B::Hooks::EndOfScope: 0
  CGI::Simple: 0
  CGI::Simple::Cookie: 0
  Carp: 0
  Data::Section::Simple: 0
  HTTP::Response: 0
  LWP::Protocol: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/motemen/LWPx-Record-DataSection.git
version: 0.01
